import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

starbucks_data = pd.read_csv('starbucks.csv')


print(starbucks_data.head())


print(starbucks_data.isnull().sum())


print(starbucks_data.describe())


corr_matrix = starbucks_data.corr(numeric_only=True)
print(corr_matrix)


sns.pairplot(starbucks_data)
plt.show()

plt.figure(figsize=(12, 8))
sns.boxplot(x='Beverage_category', y='Calories', data=starbucks_data)
plt.xticks(rotation=45)
plt.title('Calories across Beverage Categories')
plt.show()


mean_calories = starbucks_data.groupby('Beverage_category')['Calories'].mean().sort_values(ascending=False)
plt.figure(figsize=(12, 6))
mean_calories.plot(kind='bar')
plt.xlabel('Beverage Category')
plt.ylabel('Mean Calories')
plt.title('Mean Calories in Each Beverage Category')
plt.xticks(rotation=45)
plt.show()


plt.figure(figsize=(10, 6))
plt.hist(starbucks_data['Total Fat (g)'], bins=20, edgecolor='black')
plt.xlabel('Total Fat (g)')
plt.ylabel('Frequency')
plt.title('Distribution of Total Fat Content')
plt.show()


plt.figure(figsize=(10, 6))
plt.scatter(starbucks_data['Total Carbohydrates (g)'], starbucks_data['Calories'], alpha=0.5)
plt.xlabel('Total Carbohydrates (g)')
plt.ylabel('Calories')
plt.title('Calories vs. Total Carbohydrates')
plt.show()


plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()
